### ISSUE TITLE
[8] Maak sequence diagram window manager

### ISSUE THREAD

**Issue by TimonPost** [KBS-Groep-4/roei-je-rot#105]
![image](https://user-images.githubusercontent.com/19969910/70135680-d3077280-168a-11ea-95c0-9c30dc359f67.png)

**Comment by MrWaps** [comment]
Gaat 'GetUserPermissions' niet via Logic?

**Comment by MrWaps** [comment]
Iets betere beschrijvingen bij acties

**Comment by MrWaps** [comment]
![image](https://user-images.githubusercontent.com/17950921/70424931-7a601d00-1a70-11ea-9527-7a802cdf2f41.png)
Zoiets?

**Comment by MrWaps** [comment]
![image](https://user-images.githubusercontent.com/17950921/70427015-4981e700-1a74-11ea-9cdd-b78a66b7ff1f.png)
