### ISSUE TITLE
Maak domeinmodel

### ISSUE THREAD

**Issue by TimonPost** [KBS-Groep-4/roei-je-rot#36]

**Comment by BeBoRE** [comment]
- [x] Geen wedstrijd
- [x] Geen medewerker
- [x] Geen beheerder
- [x] Lid heeft niveau en rechten? (waarom moet een lid rechten hebben?)
- [ ] Boot kan misschien leden bevatten
- [x] Misschien een schade domein voor een boot (een boot kan schade hebben)
- [x] Geen multipliciteit aangegeven
