### ISSUE TITLE
Maak use case diagram

### ISSUE THREAD

**Issue by MrWaps** [KBS-Groep-4/roei-je-rot#45]

**Comment by MrWaps** [comment]
Boten beheren en overzicht beheren vallen onder verschillende use cases, is dit niet hetzelfde?

**Comment by TimonPost** [comment]
Ik denk van wel eingelijk. Want we hadden over het botenoverzicht. Deze issue kan met de ui van #61 geimplementeerd worden. Maar dan met alle sorteer boten, sorteeropties opengesteld voor de admin.

**Comment by MrWaps** [comment]
Dus het use case diagram moet aangepast worden?

**Comment by MrWaps** [comment]
Update van use case diagram staat in de drive en in het FO. Iemand ff checken?

**Comment by TimonPost** [comment]
Mooi werk, heb het na gekenek!
